export const platformDocsAdminContent = {
  console: {
    title: 'Documentation',
    subtitle: 'Manage Zenformed product documentation, categories, and articles.',
    tree: {
      products: 'Products',
      categories: 'Categories',
      articles: 'Articles',
    },
    toolbar: {
      newArticle: 'New Article',
      newCategory: 'New Category',
      delete: 'Delete',
      preview: 'Preview',
      searchPlaceholder: 'Search articles…',
    },
    wizard: {
      title: 'Create New Article',
      productLabel: 'Product',
      categoryLabel: 'Category',
      titleLabel: 'Article Title',
      authorContextLabel: 'Author Context',
      authorContextHelper: 'Add article-specific notes the AI should follow for this draft.',
      authorContextPlaceholder:
        'Example: Inside a project, open Workflow Tasks, find the task, click the paperclip, upload the file, then save the task.',
      slugLabel: 'Slug',
      pathLabel: 'Markdown File',
      cancel: 'Cancel',
      create: 'Create Article',
      creating: 'Creating…',
      error: 'Unable to create the article. Please try again.',
    },
    table: {
      title: 'Title',
      product: 'Product',
      category: 'Category',
      visibility: 'Visibility',
      lastUpdated: 'Last Updated',
      status: 'Status',
      empty: 'No articles in this category.',
      searchResultsLabel: 'Search results',
    },
    preview: {
      title: 'Article Preview',
      empty: 'Select an article to preview its metadata.',
    },
  },
  editor: {
    backToConsole: 'Back to documentation console',
    unsavedChanges: 'Unsaved Changes',
    titleLabel: 'Title',
    summaryLabel: 'Summary',
    metadataTitle: 'Metadata',
    save: 'Save',
    saving: 'Saving…',
    preview: 'Preview',
    previewing: 'Opening preview…',
    publish: 'Publish',
    publishing: 'Publishing…',
    saved: 'Saved',
    saveError: 'Unable to save changes.',
    placeholderNotice: 'This article is a placeholder and cannot be saved until a markdown file is created.',
    visibilityLabel: 'Visibility',
    categoryLabel: 'Category',
    tagsLabel: 'Tags',
    tagsPlaceholder: 'Comma-separated tags',
    readTimeLabel: 'Estimated Read Time',
    relatedArticlesLabel: 'Related Articles',
    previousArticleLabel: 'Previous Article',
    nextArticleLabel: 'Next Article',
    authorLabel: 'Author',
    slugLabel: 'Slug',
    lastUpdatedLabel: 'Last Updated',
    statusLabel: 'Status',
    publishedLabel: 'Published',
    draftLabel: 'Draft',
    contentPathLabel: 'Markdown File',
    leaveConfirm: 'You have unsaved changes. Leave without saving?',
    discardDraft: 'Discard Draft',
    discarding: 'Discarding…',
    discardDraftTitle: 'Discard Draft?',
    discardDraftBody:
      'This will permanently delete this draft article and its markdown file. This action cannot be undone.',
    discardDraftConfirm: 'Discard Draft',
    discardDraftCancel: 'Cancel',
    discardDraftError: 'Unable to discard this draft.',
  },
  articlePreview: {
    title: 'Article Preview',
    backToEditor: 'Back to Editor',
    publish: 'Publish',
    publishing: 'Publishing…',
    publishedStatus: 'Published',
    publishSuccess: 'Article published successfully.',
    publishError: 'Unable to publish this article.',
    metadataTitle: 'Article details',
    productLabel: 'Product',
    categoryLabel: 'Category',
    visibilityLabel: 'Visibility',
    statusLabel: 'Status',
    lastUpdatedLabel: 'Last Updated',
    titleLabel: 'Title',
    validationErrors: {
      title_required: 'Add a title before publishing.',
      summary_required: 'Add a summary before publishing.',
      category_required: 'Select a category before publishing.',
      content_required: 'Add article content before publishing.',
      starter_template_content: 'Replace the starter template content before publishing.',
    },
  },
  visibilityLabels: {
    public: 'Public',
    authenticated: 'Authenticated',
    staff: 'Staff',
    organization: 'Organization',
  },
  statusLabels: {
    draft: 'Draft',
    published: 'Published',
  },
  contentPlan: {
    tabLabel: 'Content Plan',
    articlesTabLabel: 'Articles',
    title: 'BuildCore Content Plan',
    description:
      'Recommended first articles for BuildCore documentation, grouped by topic. Work through the list systematically—create markdown articles from planned titles or open existing drafts.',
    table: {
      title: 'Title',
      category: 'Category',
      summary: 'Suggested Summary',
      status: 'Status',
      action: 'Action',
    },
    statusLabels: {
      not_started: 'Not Started',
      draft: 'Draft',
      published: 'Published',
    },
    createArticle: 'Create Article',
    openArticle: 'Open Article',
    statsTotal: 'Planned',
    statsNotStarted: 'Not Started',
    statsDraft: 'Draft',
    statsPublished: 'Published',
  },
} as const;
