export const platformDocsRichTextEditorContent = {
  documentLabel: 'Article content',
  placeholder: 'Start writing your documentation…',
  toolbar: {
    heading1: 'Heading 1',
    heading2: 'Heading 2',
    heading3: 'Heading 3',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    bulletList: 'Bullet list',
    orderedList: 'Numbered list',
    quote: 'Quote',
    divider: 'Divider',
    codeBlock: 'Code block',
    inlineCode: 'Inline code',
    link: 'Link',
    image: 'Image',
    callout: 'Callout',
    undo: 'Undo',
    redo: 'Redo',
  },
  linkPrompt: 'Enter URL',
  image: {
    uploadError: 'Image upload failed. Try again.',
    uploading: 'Uploading…',
    altLabel: 'Alt text',
    captionLabel: 'Caption',
    resizeHint: 'Drag corner to resize',
  },
  calloutVariants: {
    note: 'Note',
    tip: 'Tip',
    warning: 'Warning',
  },
} as const;
