export const platformAdminNavigation = {
  basePath: '/admin',
  routes: {
    home: '/admin',
    accountOwners: '/admin/users',
    accountOwnerDetail: (userId: string) => `/admin/users/${userId}`,
    organizations: '/admin/organizations',
    organizationDetail: (organizationId: string) => `/admin/organizations/${organizationId}`,
    subscriptions: '/admin/subscriptions',
    partnerPrograms: '/admin/promotions',
    partnerProgramNew: '/admin/promotions/new',
    partnerProgramDetail: (programId: string) => `/admin/promotions/${programId}`,
    partnerProgramApplications: (programId: string) => `/admin/promotions/${programId}/applications`,
    partnerApplicationDetail: (applicationId: string) => `/admin/promotions/applications/${applicationId}`,
    docs: '/admin/docs',
    docsArticleEditor: (editorId: string) => `/admin/docs/articles/${editorId}`,
  },
  api: {
    me: '/api/admin/me',
    accountOwners: '/api/admin/users',
    accountOwnerDetail: (userId: string) => `/api/admin/users/${userId}`,
    organizations: '/api/admin/organizations',
    organizationDetail: (organizationId: string) => `/api/admin/organizations/${organizationId}`,
    subscriptions: '/api/admin/subscriptions',
    partnerPrograms: '/api/admin/partner-programs',
    partnerApps: '/api/admin/partner-apps',
    partnerProgramApplications: (programId: string) => `/api/admin/partner-programs/${programId}/applications`,
    partnerApplicationDetail: (applicationId: string) => `/api/admin/partner-applications/${applicationId}`,
    partnerApplicationReview: (applicationId: string) => `/api/admin/partner-applications/${applicationId}/review`,
  },
  navItems: [
    { id: 'accountOwners', href: '/admin/users', label: 'Account Owners' },
    { id: 'organizations', href: '/admin/organizations', label: 'Organizations' },
    { id: 'subscriptions', href: '/admin/subscriptions', label: 'Subscriptions' },
    { id: 'partnerPrograms', href: '/admin/promotions', label: 'Promotions' },
    { id: 'docs', href: '/admin/docs', label: 'Documentation' },
  ],
} as const;

export type PlatformAdminNavId = (typeof platformAdminNavigation.navItems)[number]['id'];
